paths:
  /job/:
    get:
      operationId: "registered_operators.job.get.api"
      parameters:
        - name: job_id
          in: query
          type: string
          required: true
        - name: config_id
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      tags:
        - "Job"
      summary: "List out table contents"
      description: "List out contents of table by name"
      responses:
        200:
          description: "Successful list"
