id: 5
metastore_engine: athena
storage_engine: s3
clients:
  s3:
    configuration:
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
      aws_region: "{{AWS_REGION}}"
  athena:
    configuration:
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
      aws_region: "{{AWS_REGION}}"
