metastore_engine: s3
execution_engine: spark
clients:
  s3:
    configuration:
      region: us-east-1
      access_key: "AKIAQ5AXAJE5VTOUD4CQ"
      secret_key: "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"
  spark:
    configuration:
      runner:
        spark_version: "2.4.5"
        type: "kubernetes-operator"

