#  Note:  Dont forget to edit .env file to add AWS_CREDENTIALS
version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
            - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
            - $HOME/.kube/:/home/app/.kube/
        environment:
            - MASON_HOME=/mason/
        env_file:
            - .env
        image: mason:1.02
