#  Note:  Dont forget to edit .env file to add AWS_CREDENTIALS
#  Note:  Dont forget to configure .kube/config if you are using kubernetes
version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
            - $HOME/.aws/credentials:/app/.aws/credentials:ro
            - $HOME/.kube/:/app/.kube/
        environment:
            - MASON_HOME=/mason/
        env_file:
            - .env
        image: "samtecspg/mason:v1.03"

