apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: mason-spark-merge-0f5ab1a4-695d-4f16-9f6c-e3e3da286995
  namespace: default
spec:
  arguments:
  - --input_path
  - s3a://
  - --output_path
  - s3a://test
  - --job
  - merge
  - --access_key
  - AKIAQ5AXAJE5VTOUD4CQ
  - --secret_key
  - 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
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 2.4.5
    memory: 512m
    serviceAccount: spark
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.5
    memory: 512m
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  image: samtecspg/mason-spark:v2.4.5
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/jars/mason-spark-assembly-0.1.jar
  mainClass: mason.spark.Main
  mode: cluster
  restartPolicy:
    type: Never
  sparkVersion: 2.4.5
  type: Scala
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: test-volume
