paths:
  /workflow/table/validated_infer:
    post:
      operationId: "registered_workflows.table.validated_infer.api"
      tags:
        - "Workflows"
      summary: "5 step workflow for inferring table and checking if it worked then cleaning up if it didn't."
      description: "5 step workflow for inferring table and checking if it worked then cleaning up if it didn't."
      consumes:
        - application/json
      parameters:
        - name: deploy
          in: query
          required: false
          type: boolean
          default: false
        - name: run_now
          in: query
          required: false
          default: false
          type: boolean
        - name: schedule_name
          in: query
          required: false
          type: string
        - name: config_id
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
        - name: parameters
          in: body
          required: true
          schema:
            type: object
            properties:
              step_1:
                type: object
                properties:
                  config_id:
                    type: string
                  parameters:
                    type: object
                    properties:
                      database_name:
                        type: string
                      storage_path:
                        type: string
              step_2:
                type: object
                properties:
                  config_id:
                    type: string
                  parameters:
                    type: object
                    properties:
                      job_id:
                        type: string
              step_3:
                type: object
                properties:
                  config_id:
                    type: string
                  parameters:
                    type: object
                    properties:
                      query_string:
                        type: string
                      database_name:
                        type: string
              step_4:
                type: object
                properties:
                  config_id:
                    type: string
                  parameters:
                    type: object
                    properties:
                      job_id:
                        type: string
              step_5:
                type: object
                properties:
                  config_id:
                    type: string
                  parameters:
                    type: object
                    properties:
                      database_name:
                        type: string
                      table_name:
                        type: string
      responses:
        200:
          description: "Successful Schedule"

