paths:
  /table/{table_name}:
    get:
      operationId: "registered_operators.table.get.api"
      parameters:
        - name: table_name
          in: path
          type: string
          required: true
        - name: database_name
          in: query
          type: string
          required: true
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      tags:
        - "Table"
      summary: "List out table contents"
      description: "List out contents of table by name"
      responses:
        200:
          description: "Successful list"
