paths:
  /table/delete:
    post:
      operationId: "registered_operators.table.delete.api"
      tags:
        - "Table"
      summary: "Delete metastore table"
      description: "Delete metastore table"
      consumes:
        - application/json
      parameters:
        - name: table_name
          in: query
          required: true
          type: string
        - name: database_name
          in: query
          required: true
          type: string
        - name: config_id
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      responses:
        200:
          description: "Successful Delete"
          schema:
            type: "string"
