paths:
  /table/infer:
    post:
      operationId: "registered_operators.table.infer.api"
      tags:
        - "Table"
      summary: "Build schedule for schema inference and trigger"
      description: "Infer schema of data"
      consumes:
        - application/json
      parameters:
        - name: database_name
          in: query
          format: path
          type: string
          required: true
        - name: storage_path
          in: query
          format: path
          type: string
          required: true
        - name: config_id
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      responses:
        200:
          description: "Successful Infer"
          schema:
            type: "string"
