paths:
  /table/:
    get:
      operationId: "registered_workflows.table.infer.api"
      requestBody:
        content:
          application/json:
            parameters:
              type: object
      parameters:
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      tags:
        - "Job"
      summary: "List out table contents"
      description: "List out contents of table by name"
      responses:
        200:
          description: "Successful list"
