paths:
  /tables:
    get:
      operationId: "registered_operators.table.list.api"
      parameters:
        - name: database_name
          in: query
          type: string
          required: true
        - name: config_id
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: true
          type: string
      tags:
        - "Table"
      summary: "List out tables in the catalog"
      description: "List out tables in the catalog"
      responses:
        200:
          description: "Successful list"
