metastore_engine: s3
execution_engine: spark
clients:
  s3:
    configuration:
      region: us-east-1
  spark:
    configuration:
      runner:
        spark_version: "2.4.5"
        type: "kubernetes-operator"