id: 1
metastore_engine: glue
storage_engine: s3
scheduler_engine: glue
execution_engine: athena
clients:
  glue:
    configuration:
      aws_region: "{{AWS_REGION}}"
      aws_role_arn: "{{GLUE_ROLE_ARN}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  s3:
    configuration:
      aws_region: "{{AWS_REGION}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  athena:
    configuration:
      aws_region: "{{AWS_REGION}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
