basePath: /api
consumes:
- application/json
info:
  description: Swagger UI for Mason Operator API
  title: Mason Operator API
  version: 1.0.0
produces:
- application/json
swagger: '2.0'
paths:
  /configs:
    get:
      operationId: "api.config_api.get"
      parameters:
        - name: config_fie
          in: query
          type: string
          required: false
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          default: "info"
          required: false
          type: string
      tags:
        - "Config"
      summary: "List out current mason configuration"
      description: "List out mason configuration"
      responses:
        200:
          description: "Successful list"

